# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: mhuebert/docker-java-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "editor/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: npm install;
          working_directory: ~/project/editor

      - run:
          command: npx shadow-cljs server;
          working_directory: ~/project/editor
      - run:
          command: sleep 6; npx shadow-cljs release live;
          working_directory: ~/project/editor
      - run:
          command: npx shadow-cljs release trusted;
          working_directory: ~/project/editor
      - run:
          command: npx shadow-cljs release bootstrap;
          working_directory: ~/project/editor

      - run: cd editor; npm run deploy;

      - save_cache:
          paths:
            - ~/project/editor/node_modules
            - ~/project/editor/target
            - ~/.m2
          key: v1-dependencies-{{ checksum "editor/package.json" }}--{{ checksum "editor/shadow-cljs.edn"}}

      - run: cat target/shadow-cljs/shadow-cljs.log.0
