# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: timbru31/java-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "editor/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: pwd; ls; cd editor; yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "editor/package.json" }}

      # run tests!
      - run: pwd; ls; cd editor; yarn run release

